name: Sync Questie-Epoch Updates

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:       # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your private repo with write access
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 3. Add upstream remote
      - name: Add upstream
        run: |
          git remote add upstream https://github.com/trav346/Questie-Epoch.git
          git fetch upstream

      # 4. Merge upstream changes and create version tag
      - name: Merge updates & tag
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Merge upstream updates" || echo "No new commits"
          TAG=v$(date +'%Y.%m.%d-%H%M')
          git tag $TAG
          git push origin main --tags
          echo "TAG=$TAG" >> $GITHUB_ENV

      # 5. Send Discord notification with upstream link
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\":\"Questie Sync Bot\",\"embeds\":[{\"title\":\"Questie-Epoch Updates Applied\",\"description\":\"New upstream updates were merged from [trav346/Questie-Epoch](https://github.com/trav346/Questie-Epoch).\",\"color\":3066993}]}\"" \
               ${{ secrets.DISCORD_WEBHOOK }}
