name: Sync Questie-Epoch Updates

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/trav346/Questie-Epoch.git
          git fetch upstream

      - name: Merge updates & tag
        id: merge
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Merge upstream updates" || echo "No new commits"
          # Check if merge created a new commit
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse upstream/main)" ]; then
            TAG=v$(date +'%Y.%m.%d-%H%M')
            git tag $TAG
            git push origin main --tags
            echo "MERGED=true" >> $GITHUB_ENV
            echo "TAG=$TAG" >> $GITHUB_ENV
          else
            echo "MERGED=false" >> $GITHUB_ENV
          fi

      - name: Send Discord Notification
        if: env.MERGED == 'true'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\":\"Questie Sync Bot\",\"embeds\":[{\"title\":\"Questie-Epoch Updates Applied\",\"description\":\"New upstream updates were merged from [trav346/Questie-Epoch](https://github.com/trav346/Questie-Epoch).\",\"color\":3066993}]}\"" \
               ${{ secrets.DISCORD_WEBHOOK }}
